version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to your Flask app folder
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend  # Path to your Vite React app folder
    container_name: vite-frontend
    ports:
      - "3000:80"  # nginx serves static files on port 80
    depends_on:
      - backend
    restart: always
